name: CI Security Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: go build -v .

      - name: Test
        # We don't have tests yet, but this is a good step to have.
        # The -vet=off flag prevents an error if there are no test files.
        run: go test -v ./... -vet=off